Avancement front et changement de base
NhiSty/challenge-3-react pull request #11
Opened 2023-11-18 18:03 UTC by sDev67

- Ajout page login et register
- ajout navbar
- ajout systeme de toast
- ajout style tailwind et daisyUI
- suppression MUI joy de base
- modification du readme pour ajouter les explications du env example

2023-11-19 18:03 UTC, Quozul requested changes

2023-11-19 18:03 UTC, Quozul commented on src/routes/LoginPage.jsx
> +        <Input
Les inputs apparaissent en thème sombre c'est un peu bizarre quand tout le reste du site est en thème clair (à moins que ce soit un soucis sur mon navigateur)

2023-11-19 18:10 UTC, sDev67 commented on src/components/partials/NavBarButton.jsx
> +  const isConnected = localStorage.getItem("token");
hook custom ?

2023-11-19 18:30 UTC, Quozul commented on src/components/partials/NavBarButton.jsx
> +  const isConnected = localStorage.getItem("token");
Custom ou d'une lib, au choix. quelque chose comme un `useLocalStorage`, y'en a plein sur internet, je te laisse faire les recherches :)

2023-11-19 18:37 UTC, ThomasDev6 commented on src/components/partials/NavBarButton.jsx
> +          <span className="sr-only">Register</span>
Le toTranslate c'est moi qui ai fait ça pour préparer les trads.
Pour faire un gros ctrl + F comme ça on ne perd pas de trad dans la nature.
Pour l'instant c'est juste une fonction qui retourne ce que tu lui donnes

2023-11-19 19:00 UTC, sDev67 commented on src/routes/LoginPage.jsx
> +        <Input
je ne vois pas de problème 🤔

2023-11-19 19:01 UTC, sDev67 commented on src/components/partials/NavBarButton.jsx
> +  const isConnected = localStorage.getItem("token");
Sera traité dans un autre ticket

2023-11-19 22:11 UTC, ThomasDev6 commented on src/routes/RegisterPage.jsx
> +      <ToastContainer position="bottom-right" />
Ca ne devrait pas être ajouté sur les pages mais plutôt sur un Layout qui serait commun aux pages, de cette manière tu n'aurais qu'a l'ajouter qu'une seule fois.

2023-11-19 22:11 UTC, ThomasDev6 commented on src/index.jsx
Je n'aurais pas mis ça ici.
C'est le fichier pour définir les routes mais il est à la racine du dossier source.
Je l'aurais plus vu dans le dossier routes.
C'est comme ça que je le vois

2023-11-19 22:11 UTC, ThomasDev6 commented on src/App.jsx
- Je pense que ca devrait plutôt être renommé en Layout.jsx 
- De plus ca devrait-être dans le dossier components et pas à la racine.

2023-11-20 17:00 UTC, sDev67 commented on src/routes/RegisterPage.jsx
> +      <ToastContainer position="bottom-right" />
ajouté dans le App.jsx

2023-11-20 17:02 UTC, sDev67 commented on src/index.jsx
ok

2023-11-20 17:04 UTC, sDev67 commented on src/App.jsx
ok

2023-11-20 17:17 UTC, ThomasDev6 commented on src/routes/index.jsx
>      path: "/",
Pas besoin de path, tu peux le retirer

2023-11-20 17:22 UTC, ThomasDev6 submitted a review, later dismissed

2023-11-20 17:42 UTC, merged